spring.datasource.url=jdbc:postgresql://mesatech-db.cvdtbbsrhm41.us-east-1.rds.amazonaws.com:5432/mesatech
spring.datasource.username=fsr
spring.datasource.password=25XD3849MJ3v
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update