server.port=8080

# ===============================
# MICROSOFT ENTRA ID
# ===============================

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/50322baf-a2d3-4e78-ab06-d2140e9f0579/v2.0

spring.security.oauth2.resourceserver.jwt.audiences=33b8186d-805f-4136-8209-4af63d8f7388

# ===============================
# MICROSERVICIOS
# ===============================

services.orders.url=http://localhost:8081
services.catalog.url=http://localhost:8082