spring.application.name=bff

server.port=8080

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

azure.tenant-id=50322baf-a2d3-4e78-ab06-d2140e9f0579

azure.client-id=33b8186d-805f-4136-8209-4af63d8f7388

azure.client-secret=b27c9bbf-dc0f-4d22-80c3-b8a1d996ed31

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/50322baf-a2d3-4e78-ab06-d2140e9f0579/v2.0

spring.security.oauth2.resourceserver.jwt.audiences=33b8186d-805f-4136-8209-4af63d8f7388