spring.application.name=bff

server.port=8080

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

azure.tenant-id=50322baf-a2d3-4e78-ab06-d2140e9f0579

azure.client-id=77fcc9f6-bb6d-4bd2-93ed-d9fd7ec66830

azure.client-secret=iUh8Q~z_3NPAN4228-bFCXzp0fwOxA6V3GPM.diR

azure.operators-group-id=6f390e5d-82bc-4790-8c8d-f7a43e33c9f1

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/50322baf-a2d3-4e78-ab06-d2140e9f0579/v2.0

spring.security.oauth2.resourceserver.jwt.audiences=33b8186d-805f-4136-8209-4af63d8f7388